// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260830214449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("fiyat")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = false,
                            UrunAdi = "Apple Watch 7",
                            fiyat = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            UrunAdi = "Apple Watch 8",
                            fiyat = 20000.0
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            UrunAdi = "Apple Watch 9",
                            fiyat = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            Aktif = false,
                            UrunAdi = "Apple Watch 10",
                            fiyat = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            Aktif = true,
                            UrunAdi = "Apple Watch 11",
                            fiyat = 50000.0
                        },
                        new
                        {
                            Id = 6,
                            Aktif = true,
                            UrunAdi = "Apple Watch 12",
                            fiyat = 60000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
